export const presetEn = {
  peConnectionError: 'Could not connect to the local service. Retry loading; if the connection still fails, reconnect the page.',
  peReadError: 'Could not read this preset. Retry loading or refresh the preset list.',
  peRetryRead: 'Retry loading',
  peReconnect: 'Reconnect page',
  peSystemPrompt: 'System prompt sections',
  peSectionsHint: 'These templates contribute to this preset’s system prompt before the tools. Runtime variables, workspace instructions and plugin-provided guidance are assembled when the conversation runs.',
  peDynamicPrompt: 'This field is an expression; it is preserved without executing it in the editor.',
  peDshSourcePrompt: 'Tells the agent where the DSH source checkout is and keeps it separate from the current workspace. It is used when inspecting or extending DSH itself.',
  peDshWebPrompt: 'Tells the agent which Web page it is talking through, what “this page” means, and when Web changes need a rebuild or refresh.',
  peSuppressed: 'Not used',
  peCompletePersona: 'This preset uses Persona as its entire system prompt, so this section is excluded.',
  peLoading: 'Reading preset…',
  peTitle: 'Preset editor',
  peHierarchy: 'Codex mode and other presets are peers. Choose one to edit, or make an editable copy of a built-in preset first.',
  peSelect: 'Preset',
  peSelectPlaceholder: 'Choose a preset…',
  peEditable: 'This is an editable user preset.',
  peBuiltinEdit: 'Built-in presets are read-only. Create a copy to edit it.',
  peCreateCopy: 'Create editable copy',
  peCodexSection: 'Codex mode capabilities',
  peAddCodex: 'Add Codex capabilities to this preset',
  peAddCodexHint: 'Adds the Codex prompt, tools, hosted search, and remote compaction to this preset.',
  peActivityGlobal: 'Activity status is a global display setting and is shared by all presets.',
  peSaveCopy: 'Save new preset',
  peSaved: 'Saved. Select this preset in a new conversation.',
  pmGlobalSettings: 'Global settings',
  pmRefresh: 'Refresh',
  pmBuiltIn: 'Built-in',
  pmCustom: 'Custom',
  pmDiscard: 'Discard your unsaved changes?',
  pmConflict: 'This preset changed in another page or on disk. Reopen the latest version before saving.',
  pmYamlError: 'The configuration must be valid YAML. Your draft has not been saved.',
  pmErrorDetails: 'Technical details',
  pmSaveError: 'Could not complete this action. Your draft is still here.',
  pmName: 'Name',
  pmDescription: 'Description',
  pmCancel: 'Cancel',
  pmSave: 'Save changes',
} as const

export const presetZh: Record<keyof typeof presetEn, string> = {
  peConnectionError: '未能连接本地服务。请重试读取；如果仍然失败，请重新连接页面。',
  peReadError: '无法读取这个预设，请重试读取或刷新预设列表。',
  peRetryRead: '重试读取',
  peReconnect: '重新连接页面',
  peSystemPrompt: '系统提示词',
  peSectionsHint: '这些模板共同组成当前预设在工具之前的系统提示词。运行时变量、工作区指令和插件提供的说明会在会话中组装。',
  peDynamicPrompt: '此字段是动态表达式，编辑器保留原值，不执行表达式。',
  peDshSourcePrompt: '告诉 Agent DSH 源码检出目录在哪里，并与当前工作区区分开；用于检查或扩展 DSH 本身。',
  peDshWebPrompt: '告诉 Agent 当前通过哪个 Web 页面交互、“这个页面”指什么，以及 Web 修改何时需要重建或刷新。',
  peSuppressed: '未使用',
  peCompletePersona: '此预设将 Persona 作为完整系统提示词，因此不使用这一段。',
  peLoading: '正在读取预设…',
  peTitle: '预设编辑',
  peHierarchy: 'Codex 模式和其它预设处于同一级。选择一个预设编辑；内置预设先创建可编辑副本。',
  peSelect: '选择预设',
  peSelectPlaceholder: '选择一个预设…',
  peEditable: '这是可编辑的用户预设。',
  peBuiltinEdit: '内置预设只读，需要先创建副本。',
  peCreateCopy: '创建可编辑副本',
  peCodexSection: 'Codex 模式能力',
  peAddCodex: '为这个预设加入 Codex 能力',
  peAddCodexHint: '加入 Codex 提示词、工具、托管搜索和远程上下文压缩。',
  peActivityGlobal: '活动状态是全局显示设置，由所有预设共享。',
  peSaveCopy: '保存新预设',
  peSaved: '已保存，在新会话中选择此预设即可使用。',
  pmGlobalSettings: '全局设置',
  pmRefresh: '刷新',
  pmBuiltIn: '内置',
  pmCustom: '自定义',
  pmDiscard: '放弃尚未保存的修改？',
  pmConflict: '此预设已被其他页面或文件修改，请重新打开最新版本后再保存。',
  pmYamlError: '配置必须是有效 YAML，草稿尚未保存。',
  pmErrorDetails: '技术详情',
  pmSaveError: '操作未完成，填写的内容仍然保留。',
  pmName: '名称',
  pmDescription: '用途说明',
  pmCancel: '取消',
  pmSave: '保存修改',
}
